name: Verify Reference Files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-references:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive  # Initialize Shed submodule

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff==0.14.0 black
        pip install -e vendor/shed

    - name: Verify reference files are up-to-date
      run: make verify-references
